.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH dylandotnet-ide 1 "February 12, 2012" "11.2.8.3" "dylan.NET IDE"

.SH NAME
dylandotnet-ide \- A program for developing dylan.NET programs in a graphical method.

.SH SYNOPSIS
.B dylandotnet-ide
.br

.SH DESCRIPTION
This manual page explains the
.B dylandotnet-ide
program.

.SH FILES
.PP
This is the list of the most important files installed by the dylan.NET IDE Makefile or Package whichever one was used for the install. Before these paths one should add /usr/ or /usr/local/ whichever prefix was chosen in the Makefile. In package installation cases the prefix is /usr/ .
.B
.IP bin/dylandotnet-ide
The dylan.NET IDE executable script which when invoked in the terminal executes the IDE on the mono runtime.
.B
.IP lib/dylandonet-ide/dnide.exe
The main dylan.NET IDE program is what is executed by the script.
.B
.IP lib/dylandonet-ide/*support-libraries*
These are support libraries the IDE needs including the compiler and collections library.
.B
.IP share/man/man1/dylandonet.1
This is this very man page for dylan.NET IDE.


.SH VERSION
11.2.8.3

.SH "SEE ALSO"
See also http://launchpad.net/dylandotnet
