.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH dylandotnet 1 "July 8, 2011" "" "dylan.NET"

.SH NAME
dylandotnet \- A program for compiling dylan.NET source code into Mono compatible bytecode.

.SH SYNOPSIS
.B dylandotnet
.RI file-name
.br

.SH DESCRIPTION
This manual page explains the
.B dylandotnet
program.
.PP
The program
.B dylandotnet
is for compiling dylan.NET code into CLI bytecode executable and/or loadable by the mono runtime.

.SH OPTIONS
.B
.IP file-name
The file name of the file having the assembly definition and #include directives that include all the other source files is the only option to be passed on to
.B dylandotnet
in the form : "dylandotnet file-name.dyl" ;where file-name.dyl is the file mentioned before. The extension can be anything you want but .dyl will identify the file as being dylan.NET source.


.SH VERSIONS
11.2.7.1

.SH "SEE ALSO"
See also http://launchpad.net/dylandotnet
