.TH "DYLANDOTNET-MACROS" "7" "2012-12-21" "Linux" "dylan.NET Macros Manual"

.SH NAME
dylandotnet-macros \- The helper macros specification for the \fBdylan.NET\fP programming language.

.SH SYNOPSIS
This manual page is for describing the macros written in \fBM4\fP that help developers using \fBdylan.NET\fP as their language of choice.

.SH DESCRIPTION

.SH VERSION
11.2.9.8

.SH "SEE ALSO"
See also http://launchpad.net/dylandotnet, \fBdylandotnet\fP(1), \fBdylandotnet4\fP(1), \fBm4(1)\fP
